### ISSUE TITLE
thoughts from a clojure n00b

### ISSUE THREAD

**Issue by fommil** [jcf/oauth#10]
I was told about this new library as I was looking for OAuth to get me kickstarted in clojure with https://github.com/fommil/twitter-teflon/issues/1

I think there is definitely a need for this library that you're building. The existing solutions are unmaintained, have extremely confusing documentation, and are tied to specific HTTP implementations. Given that I'm learning clojure to get a feel for `core.async`/channels/go and STM, it kinda defeated the point for me to end up using http-components :confused: 

I ended up ripping the bits I needed out of `clj-oauth` so that I didn't have to pull in a `clj-http` dependency. I hope that's what your library is aiming to do.

It would be great if your library also remains HTTP agnostic. I would also recommend that you produce some documentation that explains OAuth in simple terms, as it can be very confusing. As a developer I am able to create my own quadruple of `(app token, app secret, access token, access secret)` which gets development moving... it's only afterwards that one needs to worry about implementing `(app token, app secret) => (access token, access secret)` lookup and generating the URL to show to users the first time so that the lookup actually works.

**Comment by fommil** [comment]
btw, the clj-oauth author seems open to API-breaking changes. Is there any reason why your new API couldn't be clj-oauth v2? https://github.com/mattrepl/clj-oauth/issues/50 It would be great from a community perspective if an already well-used library was continued, rather than trying to build up a new userbase.

**Comment by jcf** [comment]
One of the main reasons I created this library was to make it possible to use Aleph to send requests. I won't be adding HTTP clients to `one`.

I have written a small amount of documentation but so far this library is pretty new. Have you checked out the docstrings, and/or README in the `one` directory?

With regards to project structure and ownership, I'm happy with the setup of this project, and as such have no plans on merging or combining it with any other.

**Comment by jcf** [comment]
Closing this as its not really an issue.

Good luck with your Clojure adventure @fommil, and welcome to the community!
